### ISSUE TITLE
malware files potentially not being copied properly

### ISSUE THREAD

**Issue by yieb** [rachelrowe898/Group-1H-honeyj-rs#71]
We're getting empty zips instead of the actual files. Some attackers exit immediately after executing download commands, which means that their malware files may not be downloaded before we cut public internet connection. Other attacks do not exit immediately, indicating that there is still a further issue with our script regardless of that issue. 

Possible solutions
- is there some way to leave the container internet accessible but not ssh accessible, so that files can finish downloading?
- instead of moving files out of the downloads folder immediately, wait until the session ends before moving all files to our data folder

**Comment by stcwang** [comment]
Switched to using Hybrid Analysis on MITM log links for malware analysis due to lack of malware files
